language: generic
matrix:
  include:
    - os: osx
      osx_image: xcode8.3

before_install:
  - gem install xcpretty
  - brew tap vapor/tap
  - brew update
  - brew install vapor

script:
  # run unit tests
  - swift build --configuration release
  - swift package generate-xcodeproj
  - xcodebuild -scheme Forms -enableCodeCoverage YES test | xcpretty  # instead of swift test

after_success:
  - bash <(curl -s https://codecov.io/bash)
